version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: rss_app
    ports:
      - "80:8000"
    depends_on:
      - database
    networks:
      network1:
        ipv4_address: 173.23.1.2

  database:
    image: postgres:13.2
    container_name: rss_db
    environment:
      - POSTGRES_USER=rss_user
      - POSTGRES_PASSWORD=rss_pass
      - POSTGRES_DB=rss_app_db
    expose:
      - "5432"
    networks:
      network1:
        ipv4_address: 173.23.1.3

networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: "173.23.0.0/16"
